name: Build on OpenBSD

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/openbsd.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DARCS_VERSION: 2.18.5
    steps:
      - uses: actions/checkout@v5
      - name: Build on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          envs: 'DARCS_VERSION'
          prepare: |
            pkg_add curl ghc cabal-install
          run: |
            pwd
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
            ghc --version
            cabal --version
            set -x
            curl https://hackage.haskell.org/package/darcs-$DARCS_VERSION/darcs-$DARCS_VERSION.tar.gz -o darcs-$DARCS_VERSION.tar.gz
            tar xvzf darcs-$DARCS_VERSION.tar.gz
            cd darcs-$DARCS_VERSION
            export CABAL_DIR=/home/runner/.cabal
            cabal v2-update
            cabal v2-build exe:darcs --constraint="splitmix < 0.1.3" --extra-include-dirs=/usr/include --extra-lib-dirs=/usr/lib
            cp dist-newstyle/build/x86_64-openbsd/ghc-*/darcs-$DARCS_VERSION/build/darcs/darcs ../darcs-openbsd
            cd ..
            rm -rf /home/runner/.cabal
            rm darcs-$DARCS_VERSION.tar.gz
            rm -rf darcs-$DARCS_VERSION
      - run: ls -l
      - uses: actions/upload-artifact@v4
        with:
          name: darcs-openbsd
          path: darcs-openbsd
